### ISSUE TITLE
Connect configuration is inconsistent

### ISSUE THREAD

**Issue by DaAnda97** [Miragon/miranum#359]
Defining miranum connect application.yaml accoriding to the documentation looks like this:

```
miranum:
  camunda7.worker.defaultRetries: 0
  c7:
    auth:
      server:
        url: ${SSO_AUTH_SERVER_TOKEN_URL}
    client:
      id: ${SSO_AUTH_CLIENT_ID}
      secret: ${SSO_AUTH_CLIENT_SECRET}
```

Suggested solution: Make sure to use eather `c7 ` or `camunda7 ` consistently.
